name = "researchtool"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"

[assets]
binding = "ASSETS"
directory = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "labs_db"
database_id = "6f7cd319-27fe-4d91-8ef6-3c7b0b3055b8"
